spring:
  application:
    name: spring-cloud-gateway-006
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
server:
  port: 6001
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka/
security:
  basic:
    enabled: false
logging:
  level:
    org.springframework.cloud.gateway: debug