server:
  port: 6001
spring:
  application:
    name: spring-cloud-zuul-004
  zipkin:
    base-url: http://localhost:9001
  sleuth:
    sampler:
      percentage: 1.0
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:7001/eureka/