spring:
  application:
    name: spring-cloud-zuul-002
server:
  port: 6001
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka

zuul:
  retryable: true
  routes:
    producer:
      path: /api1/**
      serviceId: spring-cloud-producter1-002
    baidu:
      path: /bd/**
      url: http://www.baidu.com
    baiduforward:
          path: /testforward/**
          serviceId: spring-cloud-producter2-002

